default/objects/Address_Book__c/Address_Book__c.object-meta.xml
<CustomObject>
    <label>Address Book</label>
    <nameField>
        <label>Address Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Address_Book__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Address_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Cart__c/fields/Cart_Status__c.field-meta.xml
<CustomField>
    <fullName>Cart_Status__c</fullName>
    <label>Cart Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

default/objects/Cart__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Cart_Item__c.Item_Amount__c</summarizedField>
    <summaryForeignKey>Cart_Item__c.Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <label>Cart Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Cart_Item__c/fields/Beer__c.field-meta.xml
<CustomField>
    <fullName>Beer__c</fullName>
    <label>Beer</label>
    <referenceTo>Beer__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Cart_Item__c/fields/Item_Amount__c.field-meta.xml
<CustomField>
    <fullName>Item_Amount__c</fullName>
    <label>Item Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Cart_Item__c/fields/Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Item_Quantity__c</fullName>
    <label>Item Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD - {0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Order__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Order__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Order__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/CartDetailsAuraServices.cls
public class CartDetailsAuraServices {
    
    private static List<Coupon__c> getCoupon(String Name){
        List<Coupon__c> coupon = [Select Id, Price__c From Coupon__c Where Name =: Name];
        return coupon;
    }
    
    @AuraEnabled
    public static Decimal checkCoupon(String Name, String CartId){
        List<Coupon__c> couponList =  getCoupon(Name);
        if(couponList !=null && couponList.size() > 0){
            Cart__c cart = new Cart__c(Id = cartId, Coupon__c =couponList[0].Id );
            update cart;
            return couponList[0].Price__c;
        }else{
            return null;
        }
    }
    
    @AuraEnabled
    public static String createCartItems(List<String> beerList, String cartId){
        System.debug('#### beerList '+ beerList);
        List<Cart_Item__c> cartItemList = new List<Cart_Item__c>();
        List<Cart_Item__c> cartItemToUpdate = new List<Cart_Item__c>();
        Map<Id, Cart_Item__c> beerQntyMap = getCartItems(cartId);
        For(String beer : beerList){
            List<Beer__c> amount=[select Price__c from Beer__c where  id=:beer];
            Decimal amtt = amount[0].Price__c;
            system.debug(amtt);
            if(beerQntyMap != null && beerQntyMap.containsKey(beer)){
                Cart_Item__c it = beerQntyMap.get(beer);
                Cart_Item__c item = new Cart_Item__c(
                    Item_Quantity__c = it.Item_Quantity__c+1,
                    Item_Amount__c= it.Item_Amount__c + amtt,
                    Id = it.Id
                );
                cartItemToUpdate.add(item);
                system.debug(cartItemToUpdate+'jsfkhjjhsjsadjsdfjsfadsfjkadkasfhdaskdsajkdasfjadsfjk');
            }else{
                Integer Qty = 1;
                Cart_Item__c item = new Cart_Item__c(
                    Cart__c = cartId,
                    Beer__c = beer,
                    Item_Amount__c=amtt,
                    Item_Quantity__c = Qty
                );
                cartItemList.add(item);
                
            }
            system.debug(cartItemList+'jsfkhjjhsjsadjsdfjsfadsfjkadkasfhdaskdsajkdasfjadsfjk');
        }
        insert cartItemList;
        if(cartItemToUpdate != null && cartItemToUpdate.size() > 0)
            update cartItemToUpdate;
        return cartId;
    }
    
    @AuraEnabled 
    public static String getCartId(List<String> beerList){
        system.debug('cartList');
        List<Cart__c> cartList = getCart();
        if(cartList != null && cartList.size() > 0){
            createCartItems(beerList, cartList[0].Id);
            system.debug('cartlist1:'+cartList[0].Id);
            system.debug(cartList[0].Id);
            return cartList[0].Id;
            
            
        }else{
            Cart__c cart = new Cart__c(Coupon__c = getCoupon('Default')[0].Id,Cart_Id__c=String.valueOf(Math.random()),
                                       Cart_Status__c='Open', Is_Active__c=true, User__c = UserInfo.getUserId());
            insert cart;
            createCartItems(beerList, cart.Id);
            return  cart.Id;
        }
    }
    private static List<Cart__c> getCart(){
        List<Cart__c> cartList = [Select Id, Name From Cart__c Where User__c=: UserInfo.getUserId() AND Is_Active__c = true];
        system.debug('cartlist:'+cartList);
        
        return cartList;
        
    }
    
    @AuraEnabled
    public static Map<Id, Cart_Item__c> getCartItems(String CartId){
        List<Cart_Item__c> existingItemList = [Select Id, Name, Item_Amount__c,Item_Quantity__c,Cart__r.Total_Amount__c, Beer__c, Beer__r.Name From Cart_Item__c 
                                               Where Cart__c =: cartId];
        Map<Id, Cart_Item__c> beerQntyMap = new Map<Id, Cart_Item__c>();
        For(Cart_Item__c item : existingItemList){
            if(!beerQntyMap.containsKey(item.Beer__c)){
                beerQntyMap.put(item.Beer__c, item);
            }
        }
        
        return beerQntyMap;
    }
    @AuraEnabled
    public static String fetchAddressBook(){
        List<Address_Book__c> addressList = [Select Id, Name, Street__c, State__c, City__c, Postal_code__c, Country__c From Address_Book__c Where User__c =: Userinfo.getUserId()];
        return (JSON.serialize(addressList));
    }
    
    @AuraEnabled
    public static void deleteItem(String CartItemId){
        
        Database.delete(CartItemId);
    }
    
  @AuraEnabled
    public static String createOrder(String addressId,String cartId,String UserId){
        
      Order__c order = new Order__c(
                        Cart__c = cartId,
            Shipping_Address__c = addressId,
            User__c = UserId
        );
        Cart__c cart = new Cart__c(Id = CartId, Cart_Status__c='Closed', Is_Active__c=false);
        insert order;
           update cart;
        Order__c ord =[Select Id, Name From Order__c Where Id =: order.Id];
        return ord.Name+ '####' + ord.Id;
    }    
}